### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by mhaamann**
* Added support for revision of models that has dependencies for other models.
* Fixed continuation-local-storage support
* Added Mysql support
* Package clean up
* Updated docs
* Added migration example

There is still a lot to do.

### CODE REVIEW

**Comment by mhaamann** [comment]
See #4

**Comment by nielsgl** [comment]
Why did you clear out the source code in the `src/index.js` and `src/helpers.js` file? I use those as the files to write the actual code and the files in the `lib` directory are generated when running the `build` command.

**Comment by mhaamann** [comment]
I basically removed all babel code. At the time i thought the project was not active so I was cleaning out maybe a bit to aggressivly, sorry for that.
I can add it back if you like? Could you explain the benefit of using babel and the whole src and lib approach?
https://github.com/sequelize/sequelize does not use this? I though it would be good practice to copy their approach.

**Comment by nielsgl** [comment]
Ah good point :) My idea was to keep it separate and on build just create a compiled / minified version of the code in src, but I don't really feel super strong about it.

**Comment by harrisiirak** [comment]
Looks very promising. @mhaamann, @nielsgl - when this can be merged into the master?

**Comment by andrest** [comment]
I'm interested too.

**Comment by mhaamann** [comment]
Your call @nielsgl, let me know if i need to change anything to get this merged in. 
We are running it in production as of now in my company. We made tests but they are specific to our needs. 
I will try to find time to change them so it can be ported to this project.

**Comment by nielsgl** [comment]
Merged, thanks @mhaamann !

**Pull request merged**
