### PR TITLE
Solved: dates changes are not stored and exclude fields does not have…

### PR DESCRIPTION
**Pull request by ksfreitas**
This solve the issue #67

### CODE REVIEW

**Comment by nielsgl** [comment]
Thanks @ksfreitas , released as v2.6.0

**Comment by nielsgl** [comment]
@ksfreitas why do you do in the beforeHook
```
return typeof i === 'object'	        return i != null && typeof i === 'object' && !(i instanceof Date);
```

and in the afterHook
```
return typeof i != null && i === 'object' && !(i instanceof Date);
```

shouldn't they be the same?

**Comment by nielsgl** [comment]
Hm think it's a small mistake, checking `i === 'object'` doesn't make sense, I think it  `typeof i === 'object'`  should be correct 🤔

**Comment by ksfreitas** [comment]
> Hm think it's a small mistake, checking `i === 'object'` doesn't make sense, I think it `typeof i === 'object'` should be correct 🤔

You right, I didn't see this :( 
The correctly should be:
```
return i != null && typeof i === 'object' && !(i instanceof Date);
```
I will do another pull request tonight to fix this.

**Comment by nielsgl** [comment]
@ksfreitas no worries, I already fixed it and released it :)

https://github.com/nielsgl/sequelize-paper-trail/blob/master/lib/index.js#L320

**Pull request merged**
